version: 2
updates:
  # Maintain Python dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    # This ensures it respects your pyproject.toml constraints
    versioning-strategy: increase

  # Maintain GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"